services:
  traefik:
    image: traefik
    command:
      - "--api.insecure=true"
    restart: always
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./certs:/certs"
      - "./traefik.yml:/etc/traefik/traefik.yml" # Monta il file di configurazione statica
      - "./letsencrypt:/letsencrypt"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`13.48.146.47`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
        #- "traefik.http.routers.traefik-dashboard.middlewares=traefik-auth"
        #- "traefik.http.middlewares.traefik-auth.basicauth.users=user:$$apr1$$/ZRixByg$$5hi3S5VkS8xsEc124QSm7."
    networks:
      main:
        aliases:
          - traefik
          - traefik.lvh.me
  web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`rubydev.net`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=PersonalResolver"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.traefik-compress.compress=true"
      - "traefik.http.middlewares.traefik-compress.compress.defaultEncoding=gzip"
    stdin_open: true
    tty: true
    restart: always
    image: johnny97/personal:latest
    command: bash -c "bin/rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      main:
        aliases:
          - web
          - app.lvh.me

  db:
    labels:
      - "traefik.enable=false"
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      main:
        aliases:
          - db

networks:
  main:
