global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO
  filePath: /dev/stdout
  format: common

api:
  insecure: true
  dashboard: true
  debug: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"


certificatesResolvers:
  PersonalResolver:
    acme:
      email: oneill.jhon97@gmail.com
      storage: ./letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
